### ISSUE TITLE
Rule to have multiline conditional statements with conditionals on the left side

### ISSUE THREAD

**Issue by l1ving** [pinterest/ktlint#1056]
## Expected Rule behavior
The easiest way to explain is probably a code example. The top is the desired behavior.
![image](https://user-images.githubusercontent.com/17222512/104533510-8659cf00-55e0-11eb-9bfb-b4f883c78b10.png)

## Additional information
* Current version of ktlint: `0.40.0`
* Styleguide section: Not entirely sure what this is, sorry.

**Comment by Tapchicoma** [comment]
Code style does not state it explicitly, but code sample for this case has conditional on the right side: https://kotlinlang.org/docs/reference/coding-conventions.html#formatting-control-flow-statements

I think right side usage for conditionals is preferable, because then you will have same approach for operators as well and will not do such mistake:
```kotlin
val foo = 3
    + 2
println(foo) // prints 3
```

Imho, if you still prefer usage on the left, better to create a custom rule.

**Comment by l1ving** [comment]
> Imho, if you still prefer usage on the left, better to create a custom rule.

I'm probably not knowledgeable enough to do that, but thank you. I didn't really consider operators, I avoid multilining those

**Comment by paul-dingemans** [comment]
> Imho, if you still prefer usage on the left, better to create a custom rule.

I agree with this as long as there is no widespread request to add such functionality. As @Tapchicoma indicated it has side effects on operators like `+`. Other examples to be expected is that code like:
```
    val anchor = owner.firstChild!!
        .siblings(forward = true)
        .dropWhile { it is PsiComment || it is PsiWhiteSpace }
    val s = foo()
        ?: bar
    val s = foo()
        ?.bar
```
would transform to:
```
    val anchor = owner.firstChild!!.
        siblings(forward = true).
        dropWhile { it is PsiComment || it is PsiWhiteSpace }
    val s = foo() ?:
        bar
    val s = foo()?.
        bar
```

@l1ving Would you mind closing this issue?
