### ISSUE TITLE
Format (-F) command is not honouring the baseline file

### ISSUE THREAD

**Issue by girish3** [pinterest/ktlint#1072]
I created a baseline file from the below command,
`ktlint --baseline=ktlint-baseline.xml`

and I could see no errors are reported if I run it again since there are no changes against the baseline file. But when I add the format  flag, the baseline file is getting ignored and the terminal spit out the fixed errors,

`ktlint --baseline=ktlint-baseline.xml -F` does not work as expected!

Can anyone help?

**Comment by Tapchicoma** [comment]
Current baseline implementation does not prevent linting, but rather it just suppresses found errors.

So in case of `-F` flag - format is still happening and, if non-formattable error present in the baseline still occurs, it will be printed. Another issue with format and baseline - it relies on error position in text file, so when format changes Kotlin file, errors positions may be updated.

**Comment by nailshakurov** [comment]
I also ran into this inconvenience. I am looking for a workaround.

**Comment by Kardelio** [comment]
same! ^^^ would love if we could filter formatting with the baseline file

**Comment by paul-dingemans** [comment]
> same! ^^^ would love if we could filter formatting with the baseline file

Please feel free to contribute a PR ;-)

**Comment by Goooler** [comment]
@paul-dingemans Could you validate this issue? I believe fixed in `0.49.0-SNAPSHOT`.

**Comment by paul-dingemans** [comment]
This issue should not be marked as bug. It can be seen as an enhancement. A possbile way to solve would be as follows:
* pass baseline  to `KtlintRuleEngine`
* parse code to AST as usual
* Dynamically add a suppress annotation of a new type (for example `@BaselineSuppress("ktlint:rule-id")`) to the AST. Add this new type of annotation to the `SuppressionLocatorBuilder`.
*  lint/format the code as usual.
    * Errors for code suppressed in the baseline will no longer be reported due to the dynamically added suppression.
    * In case some other line of code in the files is autocorrected, the error which was suppressed in the baseline will not be affected anymore because of the dynamically added suppression.

* In `format` function:
    * Update baseline. Due to format of lines of code which were not suppressed, the line/column of baseline errors might have changed.
    * when writing the output in the `format` function, filter out the dynamically added suppression (e.g. remove all `@BaselineSuppress` annotations.

Introduction of the annotation above also have other implecations that need to be mitigated:
* Dynamically adding the annotation affects the line numbers of errors on lines below that annotation
* Special care has to be given to the `AnnotationRule`. Dynamically inserting an annotation with an argument  `@BaselineSuppress("ktlint:rule-id")` on top of a construct that was already annotated might cause all annotations to be wrapped to separate lines. This is unwanted because the annotation will be not be persisted.

This change will require a considerable refactoring. I will not implement it myself as I am not convinced that it is worth to maintain the baseline functionality in the long term. I am a strong believer that a project that implements ktlint also should take the effort to resolve existing problems.
