### ISSUE TITLE
ParseException: 4:1 Expecting a top level declaration

### ISSUE THREAD

**Issue by WebTiger89** [pinterest/ktlint#1347]
I'm using spotless:

`spotless {
  kotlin { ktlint("0.43.2") }
`

> 1:1 Expecting a top level declaration
com.pinterest.ktlint.core.ParseException: 1:1 Expecting a top level declaration
	at com.pinterest.ktlint.core.KtLint.prepareCodeForLinting(KtLint.kt:200)
	at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:377)
	at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:359)

the file that is failing: project-level _test.gradle.kts_:
`plugins {
    id("com.github.ben-manes.versions") version "0.41.0"
}
`

**Comment by romtsn** [comment]
please provide the contents of `test.gradle.kts` if possible

**Comment by WebTiger89** [comment]
I did:
`plugins {
id("com.github.ben-manes.versions") version "0.41.0"
}`

**Comment by romtsn** [comment]
this is the only line you have in that gradle file?

**Comment by romtsn** [comment]
thanks, no this looks like a ktlint issue.

**Comment by WebTiger89** [comment]
@romtsn Do you need a sample code?

**Comment by paul-dingemans** [comment]
@WebTiger89 A sample project would be welcomed.

**Comment by WebTiger89** [comment]
@paul-dingemans Sorry for the late reply. Just open project and run spotlessCheck task.
[configuration-plugin.zip](https://github.com/pinterest/ktlint/files/8035515/configuration-plugin.zip)

**Comment by paul-dingemans** [comment]
I have looked into this for a few hours. But to be honest, I really don't understand what it happening. I am not very familiar with Gradle nor spotless. But I have a few observations that might help you in finding the problem:

```Expecting a top level declaration
com.pinterest.ktlint.core.ParseException: 1:1 Expecting a top level declaration
```
This usually means that the file that is being processed by KtLint is not recognized as valid Kotlin (Script). The code that parse the file is coming from an external library: `org.jetbrains.kotlin.com.intellij.psi.PsiFileFactory`.

You indicated that the problem is related to the plugin `com.github.ben-manes.versions`. When searching in you example project, I only did found a reference in file `gradle/kotlin/dsl/plugins/_231ddaf56e79ad886893b7bd0c32f89b/PluginSpecBuilders.kt`. But why would you want to scan kotlin code that is included via dependencies?

If I just copy the four kts files from your example project to another folder and run ktlint on them, no error is produced.

**Comment by paul-dingemans** [comment]
Closed due to lack of response in last 28 days.

**Comment by pablobaldez** [comment]
I have this problem after updating to kotlin 1.6.21 and adding compile flags to use `context` receiver ([link](https://github.com/Kotlin/KEEP/blob/master/proposals/context-receivers.md#:~:text=In%20Kotlin%2C%20you%20can%20define,a%20dispatch%20receiver%20fun%20Entity.))

this is the method triggering the error
```kotlin
context(TestScope)
@ExperimentalCoroutinesApi
inline fun <T> Flow<T>.emissionsOn(crossinline triggerEmissions: () -> Unit): List<T> {
    val emissions = mutableListOf<T>()
    val job = launch(UnconfinedTestDispatcher(testScheduler)) {
        toList(emissions)
    }
    triggerEmissions()
    runCurrent()
    job.cancel()
    return emissions
}
``` 

the compiler indicates the error on `context(TestScope)` line
my gradle file is configured like that
```
kotlinOptions {
    jvmTarget = '1.8'
    freeCompilerArgs = freeCompilerArgs + "-Xcontext-receivers"
}
```
