### ISSUE TITLE
Unexpected whitespace

### ISSUE THREAD

**Issue by nuhkoca** [pinterest/ktlint#1458]
I have a function that doesn't fit into single line so I break the line but `Ktlint` throws unexpected whitespace exception.

```kotlin
fun bindVeryLongNamedFragment():
    VeryLongNamedFragment
```

## Expected Behavior

Ktlint won't throw exception

## Observed Behavior

Ktlint will throw exception

## Your Environment

* Version of ktlint used: 0.46.0-SNAPSHOT
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Ktlint Gradle Plugin 10.2.1
* Version of Gradle used (if applicable): 7.4.2
* Operating System and version: MacOS Monterey

**Comment by paul-dingemans** [comment]
In my opionion, this is an exceptional case. If the function had a parameter, it would make sense to wrap the parameters to the next line and then there would be enough space for the return type. So instead of allowing/ignoring the situation by the rule, I would like to use the supression hints to disable the rule.

First work around would be to put everything on one line and disable the max-line-length rule for this line.
```
fun bindVeryLoooooooooooooooooooooogNamed(): VeryLongNamedFragment {} // ktlint-disable max-line-length
```
This is most likely unwanted from code readability perspective

The next workaround would be to break the function signature and disable the experimental rule for the function return type spacing.
```
fun bindVeryLoooooooooooooooooooooogNamed(): // ktlint-disable experimental:function-return-type-spacing
    VeryLongNamedFragment {}
```
This of course is intolerable ugly as that comment is way longer than the return type which is pushed down.

The block suppression below is less ugly but would in my personal code bases still be unacceptable:
```
/* ktlint-disable experimental:function-return-type-spacing */
fun bindVeryLoooooooooooooooooooooogNamed():
    VeryLongNamedFragment {
    // body
}
/* ktlint-enable experimental:function-return-type-spacing */
```

A more tolerable workaround would be if the `@Suppress` annotation could be used to suppress any ktlint rule:
```
@Suppress("ktlint:experimental:function-return-type-spacing")
fun bindVeryLoooooooooooooooooooooogNamed():
    VeryLongNamedFragment {}
```
Currently this is not yet supported by ktlint, but it is easy to achieve.

Would the `@Suppress` workaround be okay for you?

**Comment by nuhkoca** [comment]
Hey @paul-dingemans, thanks for reply. I tried to use `@Suppress` but when I run `./gradlew ktlintFormat`, ktlint alway formats that line to single line.

**Comment by paul-dingemans** [comment]
You missed this remark:
> Currently this is not yet supported by ktlint, but it is easy to achieve.

**Comment by HexagonSun** [comment]
> In my opinion, this is an exceptional case. If the function had a parameter, it would make sense to wrap the parameters to the next line and then there would be enough space for the return type. 

I've just ran into the same issue after upgrading to 0.49 where `function-return-type-spacing` was promoted to the standard rule set.

@paul-dingemans: Is it _really_ a corner case?  IMO with extension functions and generic parameters you very quickly run into the situation where the return type doesn't fit on the same line anymore, and in these cases adding a line-break seems the most natural thing for me. Here's a real example from my code base:
```
private fun <K> Map<K, List<ProjectWorkflowStep>>.sortedByLatestDueDateTime():
    List<Pair<K, List<ProjectWorkflowStep>>> =

    …
```
With a line-length of 120 characters, this does not fit on one line (the `=` is just over the threshold). While the map-of-lists is a bit ugly, this signature ist not _that_ far fetched, IMO. 
There is a workaround using type aliases, but introducing them just to make the linter happy does not feel right either (it's a small utility method, the declared return type is never used again: at the call site the return value is immediately destructured using `.map { (key, value) -> …` ).

While I very much like the rule per se – and would like to enable it for other, more regular cases. As it is, I had to add @Suppress statements all over the place, and ultimately decided to disable the rule instead.

**Comment by paul-dingemans** [comment]
> With a line-length of 120 characters, this does not fit on one line (the `=` is just over the threshold). While the map-of-lists is a bit ugly, this signature ist not _that_ far fetched, IMO.
> There is a workaround using type aliases, but introducing them just to make the linter happy does not feel right either (it's a small utility method, the declared return type is never used again: at the call site the return value is immediately destructured using `.map { (key, value) -> …` ).

Using type aliases solely to statisfy the linter would indeed be a bad idea.

When writing the rules, it is all about trade offs. In most cases I would say that having an unneeded line break between the colon and the return type is more harmfull than a couple of situations in which it could come in handy. As always, there are always code bases in which this happens more frequently and in which it actually is harmfull. So that is why the annotations are usefull.

But the suppress annotation also cause noise that you want to avoid as much as possible.
- If you only have a couple of files in which this happens a lot then using `@file:Suppress(...)` might be a better solution
- If it only occurs in a certain module/package then you consider to disable the rule only for files in a specific directory
- You can use a little hack by adding a `//` after the colon
```
private fun <K> Map<K, List<ProjectWorkflowStep>>.sortedByLatestDueDateTime(): //
    List<Pair<K, List<ProjectWorkflowStep>>> =
```
- If it is widespread throughout the entire code base then disabling the rule like you did, might be the best way.
