### ISSUE TITLE
Respect @Suppress("RemoveCurlyBracesFromTemplate")

### ISSUE THREAD

**Issue by JLLeitschuh** [pinterest/ktlint#157]
If I have some code like this:
```kotlin
val prettyString = computeSomeString()

@Suppress("RemoveCurlyBracesFromTemplate")
val expectedPrint = """
|${TAB}==========================================================
|${TAB}=                     GRAPH OVERVIEW                     =
|${TAB}==========================================================
|${TAB}Nodes: 2
|${TAB}Links: 2
|${TAB}
|${TAB}Link Breakdown:
|${TAB}${TAB}[Aout1->Bin1]; Weight: 1.0, Capacity: 10000.0
|${TAB}${TAB}[Bout1->Ain1]; Weight: 1.0, Capacity: 10000.0
""".trimMargin()

assertEquals(expectedPrint, prettyString)
```

Ktlint reformats it to this:
```kotlin
@Suppress("RemoveCurlyBracesFromTemplate")
val expectedPrint = """
|$TAB==========================================================
|$TAB=                     GRAPH OVERVIEW                     =
|$TAB==========================================================
|${TAB}Nodes: 2
|${TAB}Links: 2
|$TAB
|${TAB}Link Breakdown:
|${TAB}$TAB[Aout1->Bin1]; Weight: 1.0, Capacity: 10000.0
|${TAB}$TAB[Bout1->Ain1]; Weight: 1.0, Capacity: 10000.0
""".trimMargin()
```

The reason that I've put on the `@Suppress("RemoveCurlyBracesFromTemplate")` is because I want to have the "fake" indentation to be consistent. As you can see the character count between `$TAB` is off by two characters from `${TAB}`. I'm going for readability in my test over what is the "most correct".

**Comment by AleksandrSl** [comment]
Can I try to implement this one?

**Comment by shyiko** [comment]
@AleksandrSl That would be great! 
As a starting point - take a look at https://github.com/shyiko/ktlint/blob/master/ktlint-core/src/main/kotlin/com/github/shyiko/ktlint/core/KtLint.kt#L397. 

I'm note sure how to map compiler warnings to rule ids, though (RemoveCurlyBracesFromTemplate to [string-template](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StringTemplateRule.kt#L10) in this case; note that these two have different scope so in order to support `@Suppress` rules will need to have access to suppression ranges complicating the matter).

Current workaround is to use [`/* ktlint-disable string-template */`](https://github.com/shyiko/ktlint#how-do-i-suppress-an-error).

P.S. If you feel like helping adding missing https://kotlinlang.org/docs/reference/coding-conventions.html & https://android.github.io/kotlin-guides/style.html rules is of (much) greater value then fixing this particular issue.

**Comment by AleksandrSl** [comment]
@shyiko I thought to handle suppress annotation directly in [this rule](https://github.com/shyiko/ktlint/blob/db46520032207472cbdd90621c0f4f93ad5528d1/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StringTemplateRule.kt#L10), however your suggestion seems more natural

**Comment by shyiko** [comment]
@AleksandrSl I guess that would be OK too (+ easier to implement). 

NOTE: `@Suppress` can be applied [pretty much anywhere](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-suppress/index.html).

**Comment by arturbosch** [comment]
@AleksandrSl you can check out how we suppress issues by annotations [@detekt](https://github.com/arturbosch/detekt/blob/master/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/Suppressible.kt), maybe it helps.

**Comment by AleksandrSl** [comment]
@shyiko Hi, I've come up with two draft implementations
https://github.com/AleksandrSl/ktlint/pull/2 - this one acts by adding `SupressHint`s. Disadvantage - we suppress the whole string-template rule.
https://github.com/AleksandrSl/ktlint/pull/1 - this one acts in string-template rule. Disadvantage - we should scan all annotated parents of each node.

**Comment by AleksandrSl** [comment]
Hi @shyiko, did you have time to see proposed implementations, or this issue will be resolved by global changes in the way ktlint works?

**Comment by shyiko** [comment]
I'd go with https://github.com/AleksandrSl/ktlint/pull/2 (only it should be [it.toSet() instead of setOf()](https://github.com/AleksandrSl/ktlint/pull/2/files#diff-25d2db63b28b3096a8738c2116568582R407) if I'm reading it right).

**Comment by blcooley** [comment]
Doing some triage, it looks like the PR [AleksandrSI#2](https://github.com/AleksandrSl/ktlint/pull/2) has been merged. Can this issue be closed @shyiko @AleksandrSl ?

**Comment by AleksandrSl** [comment]
@blcooley It was merged only in my fork) Here https://github.com/shyiko/ktlint/pull/263 is not merged yet. @shyiko what should we do with it?

**Comment by Raibaz** [comment]
Doing some triage, looks like #263 can be merged and this issue closed, @shyiko WDYT?

**Comment by Tapchicoma** [comment]
PR with support was merged.
