### ISSUE TITLE
Traversing the directory hierarchy is broken on Windows as of version 0.47

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [pinterest/ktlint#1600]
## Expected Behavior

Running `ktlint` w/o specifying any input files previously made it search for `*.kt` and `*.kts` files, starting from the current directory, e.&nbsp;g.:

```console
$ ./ktlint
14:54:01.402 [main] INFO com.pinterest.ktlint.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
10:56:53.905 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - 6821ms / 14 file(s) / 167 error(s)
```

This behaviour still holds when `ktlint` is run from the command line on _Linux_ or _Mac OS X_.

## Observed Behavior

Yet, using just the very same command line switches on _Windows_ (i.&nbsp;e. when running `ktlint` from _Git Bash_) results in no input files being found:

```console
15:01:09.889 [main] INFO com.pinterest.ktlint.internal.KtlintCommandLine - Enable default patterns [**\\*.kt, **\\*.kts]
15:01:10.457 [main] ERROR com.pinterest.ktlint.internal.KtlintCommandLine - No files matched [**\\*.kt, **\\*.kts]
```

This is a clear regression against version **0.46.1** and, apparently, has been caused by the [recent changes](https://github.com/pinterest/ktlint/pull/1533) which re-enable (sort of &mdash; see #1601) the parsing of [_Ant_-like path patterns](https://www.jetbrains.com/help/teamcity/wildcards.html#Antlike+Wildcards) (e.g.: `**/*.kt`) &mdash; which was broken in version **0.46.1**.

## Steps to Reproduce

1. Download the fat JAR from https://github.com/pinterest/ktlint/releases/tag/0.47.0.
2. Run the far JAR against any non-empty codebase on Windows:
    ```bash
    java -Xmx512m --add-opens java.base/java.lang=ALL-UNNAMED -jar ktlint
    ```
## Your Environment

* Version of ktlint used: **0.47**
* Relevant parts of the `.editorconfig` settings: none
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): **CLI**
* Version of Gradle used (if applicable): N/A
* Operating System and version:
   * `MINGW64_NT-10.0-19043 unit-725 3.3.4-341.x86_64 2022-05-09 11:56 UTC x86_64 Msys`
   * `Linux unit-725 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux`

**Comment by paul-dingemans** [comment]
I am not sure whether I can fix this soon. Biggest problem for me is that I do not have access to a Windows machine on which I can test. Also the unit testing on the windows-look-a-like-filesystem is limited. Is anybody willing to help me out by either fixing the problem or run tests whenever I have a possible fix ready?

**Comment by 0x6675636b796f75676974687562** [comment]
> Biggest problem for me is that I do not have access to a Windows machine on which I can test. Also the unit testing on the windows-look-a-like-filesystem is limited.

It doesn't actually matter whether any of the unit tests is successful on your or my PC, be it Windows or Linux. The only source of truth should be the CI server, and, since you're using GitHub, you can easily have one. Only when each commit to the project gets tested on the CI infrastructure can you be sure that nothing gets broken.

Please read on about [Building and testing Java with Gradle](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle), and also about [Using a matrix for your jobs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs).

There's also plenty of [examples](https://github.com/search?l=YAML&q=gradle%2Fgradle-build-action&type=Code) on how to use the `gradle/gradle-build-action`.

**Comment by paul-dingemans** [comment]
Yes, that is already in place. But you don't have an actual filesystem in CI. So we use jimfs to simulate that. The windows version of it, lacks some functionality. So certain unit tests can not run on CI.

**Comment by 0x6675636b796f75676974687562** [comment]
@paul-dingemans, thank you for the clarification.

Correct me if I'm wrong, but file system operations are allowed when using _GitHub Actions_ &mdash; you can create/delete/append files, traverse directories etc. 

Probably, `FileUtilsFileSequenceTest` could be extended to use not only `jimfs` but also the default file system. If you think the resulting test would be too heavy, then it could be extracted into a separate GitHub workflow. Or am I missing something here?

**Comment by paul-dingemans** [comment]
I would not expect it to be too heavy. I just have no experience with it. Most code in this project was written before I got involved.

If you have a reference to a project where something like this is set up, I would be happy to use that. Otherwise, I have to investigate it myself. Of course, it might take longer as a result of that. So any help is appreciated.

**Comment by 0x6675636b796f75676974687562** [comment]
@paul-dingemans, I'll try to refactor a unit test and give you a clue how a default file system can be tested.

In a short while.

**Comment by paul-dingemans** [comment]
> @paul-dingemans, I'll try to refactor a unit test and give you a clue how a default file system can be tested.
> 
> In a short while.

That would really be appreciated.

**Comment by paul-dingemans** [comment]
I think I have found the problems with the Unit tests for windows. It was caused by incorrect logic in the `FileUtils.kt` which has been present there for a long time. See #1615 for fixes related to #1600 and #1601.

**Comment by paul-dingemans** [comment]
Hi @0x6675636b796f75676974687562 ,

As far as I can see, I have fixed the problem with path traversing and the ant-path parsing (#1601). I would be grateful if you could test latest snapshot (see https://pinterest.github.io/ktlint/install/snapshot-build/) to see whether the problems are resolved on Windows.

**Comment by paul-dingemans** [comment]
> Hi @0x6675636b796f75676974687562 ,
> 
> As far as I can see, I have fixed the problem with path traversing and the ant-path parsing (#1601). I would be grateful if you could test latest snapshot (see https://pinterest.github.io/ktlint/install/snapshot-build/) to see whether the problems are resolved on Windows.

@0x6675636b796f75676974687562 Andrey,
Can you please check this on Windows? It is the last issue for which I am waiting for a confirmation so that version 0.47.1 can be released.

**Comment by unix-junkie** [comment]
@paul-dingemans, I'll test and get back to you tomorrow morning.

**Comment by 0x6675636b796f75676974687562** [comment]
Tested on Windows, works like a charm.

Thank you @paul-dingemans.

**Comment by CokieForever** [comment]
Not sure if you fixed that as well, but when using `**`, only files under the current directory are searched. That leads to some confusion with patterns like `../src/**/*.kt` finding no file at all, while for example `../src/main/kotlin/com/package/*.kt` would find (some) files.

Little demonstration: [ktlint_test.zip](https://github.com/pinterest/ktlint/files/9526238/ktlint_test.zip)

```
ktlint_test> ktlint *.kt
ktlint_test\Test.kt:2:16: Unnecessary trailing comma before ")" (trailing-comma-on-declaration-site)

ktlint_test> ktlint **/*.kt
ktlint_test\Test.kt:2:16: Unnecessary trailing comma before ")" (trailing-comma-on-declaration-site)

ktlint_test> cd subdir

ktlint_test\subdir> ktlint ../*.kt
ktlint_test\subdir\..\Test.kt:2:16: Unnecessary trailing comma before ")" (trailing-comma-on-declaration-site)

ktlint_test\subdir> ktlint ../**/*.kt
12:40:22.807 [main] ERROR com.pinterest.ktlint.internal.KtlintCommandLine - No files matched [../**/*.kt]
```

**Comment by unix-junkie** [comment]
@CokieForever, please enclose the last argument in double quotes to make sure it doesn't get expanded by the shell.

**Comment by CokieForever** [comment]
@unix-junkie I'm not sure what you mean, the argument is logged by ktlint and seem perfectly fine. Besides I'm on Windows like the OP, so shell expansion is not really a thing 😄 And even if by some strange phenomenon it was indeed expanded, it should still work, right? 🤔 

For the sake of completeness I tried with double quotes anyway, and it made no difference. I also tried with absolute paths, also no difference. From what I can gather from the debug logs the issue is caused by the `rootDir` parameter of `FileSystem.fileSequence()`: https://github.com/pinterest/ktlint/blob/master/ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt#L46

```
ktlint_test\subdir> ktlint "../**/*.kt" --debug
16:05:01.441 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - Discovered reporter with "baseline" id.
16:05:01.443 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - Discovered reporter with "checkstyle" id.
16:05:01.444 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - Discovered reporter with "json" id.
16:05:01.445 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - Discovered reporter with "format" id.
16:05:01.445 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - Discovered reporter with "html" id.
16:05:01.445 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - Discovered reporter with "plain" id.
16:05:01.445 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - Discovered reporter with "sarif" id.
16:05:01.446 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - Initializing "plain" reporter with {verbose=false, color=false, color_name=DARK_GRAY, format=false}
16:05:01.472 [main] DEBUG com.pinterest.ktlint.internal.FileUtils - Start walkFileTree for rootDir: 'C:\ktlint_test\subdir'
   include:
[      - sun.nio.fs.WindowsFileSystem$2@44a7bfbc]
   exlcude:
[]
16:05:01.477 [main] DEBUG com.pinterest.ktlint.internal.FileUtils - Discovered 0 files to be processed in 4 ms
16:05:01.484 [main] ERROR com.pinterest.ktlint.internal.KtlintCommandLine - No files matched [../**/*.kt]
```

**Comment by paul-dingemans** [comment]
Are you sure that you are using version `0.47.1`?  In the logging above, I see a typo `exlcude` which did exist in `0.47.0` but was fixed in `0.47.1`. In `0.47.1`, you should have seen a warning that ".." may not be used when it results in a reference outside the current directory (https://github.com/pinterest/ktlint/blob/master/ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt#L283).

**Comment by CokieForever** [comment]
No sorry I was using 0.47.0, I hadn't realized 0.47.1 was out. I can see the error message with 0.47.1, and apparently we went back to WARN instead of ERROR as well.
```
ktlint_test\subdir> ktlint ../**/*.kt
16:46:19.763 [main] WARN com.pinterest.ktlint.internal.FileUtils - On WindowsOS the pattern '../**/*.kt' can not be used as it refers to a path outside of the current directory
16:46:19.790 [main] WARN com.pinterest.ktlint.internal.KtlintCommandLine - No files matched [../**/*.kt]
```
Does this mean the issue will not get fixed then? Using parent directories would be an effective workaround for https://github.com/pinterest/ktlint/issues/1288 😞

**Comment by CokieForever** [comment]
Nevermind, nevermind, apparently https://github.com/pinterest/ktlint/issues/1288 was fixed in 0.47.1 as well, or at least it works for me again 😄

**Comment by tommus** [comment]
@paul-dingemans I think the problem mentioned by @CokieForever still remains. The only difference in my case is - I am using Mac OS X machine.

I have a `build.gradle` file in a module defined in a subdirectory of the `$rootDir` of my project. I am interested in running the static analysis against all the modules and due to the error explained by @CokieForever - it is impossible.

I've tested ktlint `0.47.1` which @CokieForever mentioned as working in his case. With no luck. I've also tested the most recent one - `0.49.0` with exact same result. I've changed either gradle dependency and a ktlint CLI binary installed on my machine.

The `FileUtils` class point to a current directory as a starting point of file tree walk and finds to files to scan.

Here is the output of a debug logger:

```
DEBUG com.pinterest.ktlint.internal.FileUtils - Start walkFileTree for rootDir: '/Users/tommus/Code/android/my-project-android/infrastructure/static-analysis'
   include:
[      - sun.nio.fs.UnixFileSystem$3@11a9e7c8]
   exclude:
[]
```

I have tested multiple variants of the arguments:
- `**/*.kt`
- `../../**/*.kt`
- `$rootDir/**/*.kt` (as it is a custom gradle task)

In each case - the starting point of the file walk was defined incorrectly and scanned only the files from the current directory (`pwd` in case of ktlint CLI and a `build.gradle` parent directory in case of Gradle task).

**Comment by paul-dingemans** [comment]
> I have a `build.gradle` file in a module defined in a subdirectory of the `$rootDir` of my project. I am interested in running the static analysis against all the modules and due to the error explained by @CokieForever - it is impossible.

I would assume that `build.gradle` is actually `build.gradle.kts`. If you do not supply any glob at the command then this file is picked up, even in case it is located in the directory from which you execute the command. Your sample globs all end with `*.kt` which will never match a file ending with `*.kts`. Can you post the exact (and entire) command that you execute if the problem persists?

**Comment by jokinol** [comment]
Same here, I just updated from `0.39.0` to `0.49.0` and noticed the same issue. Running it on MacOS machine and seems that this relates to bash shell somehow because didn't notice any issues with zsh or fish.

It is quite easy to reproduce with bash: just run `ktlint ../project-directory/src/**/*.kt` in some subdirectory other than `project-directory`, in `project-directory` it works as expected. This gives you `09:00:51.660 [main] WARN com.pinterest.ktlint.cli.internal.KtlintCommandLine - No files matched [../project-dir/src/**/*.kt]` error (should that log level be ERROR btw?). As said, fish and zsh works fine so it was a bit hard to catch, because everything worked in command line, but failed when I tried to run ktlint in bash script.

Hope this helps.

**Comment by tommus** [comment]
@paul-dingemans - in this exact project, all the gradle files are implemented in groovy. So the assumption about `build.gradle.kts` is wrong. Also, I am interested in scanning for `.kt` files, so the problem is not with the input (I simply do not bother about `.kts` files).

I've also tried to use the kltint cli with no explicitely passed input globs. With exactly same result of no files found due to the fact, the traversal started in the module's directory not in the project's directory.

@jokinol described how one can reproduce the problem. There is no difference whether you will run the ktlint cli from the command line or try to use gradle to actually call it.

In addition to what @jokinol wrote, I experience this problem with Z Sheel (zsh) - so the guess about the problem being shell-dependent, might be unlucky guess.

**Comment by paul-dingemans** [comment]
> in this exact project, all the gradle files are implemented in groovy. So the assumption about build.gradle.kts is wrong.

Tnx for clarifying this false assumption. I can now reproduce the problem and will create a new issue for fixing it.

**Comment by paul-dingemans** [comment]
The problem is now fixed via #2002 / #2004. Can you please verify using the [snapshot](https://pinterest.github.io/ktlint/install/snapshot-build/) that the problem is really gone for your use cases?

**Comment by jokinol** [comment]
For some reason I was not able to execute `shadowJarExecutable` task with 0.49.0 (Unable to generate signature for '/Users/<user>/src/ktlint/ktlint-cli/build/run/ktlint' as no signatory is available to sign) but I used commit `bc39250a0ed84f72b091b52e2b4d85737f93ce97` (one before your PR) and generated executable jar and it was broken as expected:

```
bash-3.2$ java -jar /Users/<user>/src/ktlint/ktlint-cli/build/libs/ktlint-cli-0.49.1-SNAPSHOT-all.jar ../<project>/src/**/*.kt
08:48:07.294 [main] WARN com.pinterest.ktlint.cli.internal.KtlintCommandLine - No files matched [../<project>/src/**/*.kt]
bash-3.2$
```

But in `master` it worked:

```
bash-3.2$ java -jar /Users/<user>/src/ktlint/ktlint-cli/build/libs/ktlint-cli-0.49.1-SNAPSHOT-all.jar ../<project>/src/**/*.kt
bash-3.2$
```

So I can confirm that at least it works on my machine.

**Comment by tommus** [comment]
@paul-dingemans - I've tested `0.49.1-SNAPSHOT` in my multi-module project with this nested ktlint module configuration and it seems to work fine. It resolves the files starting from the project root directory.

@jokinol - regarding the `shadowJarExecutable` error, more recent version of ktlint started using updated version of shadow library that creates a fatjar package. This library added a new (shadow) runtime configuration. It's a backward-incompatible change as ktlint become incapable of selecting proper runtime configuration on it's own, so you have to provide some help.

It's enough to define the attributes within the module `dependencies`:

```groovy
dependencies {

    // (...)

    // The attribute workaround below solves the problems introduced by the updated shadow library.
    // @see https://github.com/pinterest/ktlint/issues/1114
    // @see https://github.com/JLLeitschuh/ktlint-gradle/issues/458

    add("ktlint", tests.ktlint) {
        attributes {
            attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling, Bundling.EXTERNAL))
        }
    }
}
```

**Comment by paul-dingemans** [comment]
@jokinol @tommus Tnx for confirming.

**Comment by jokinol** [comment]
Could you release 0.49.1 kindly please? I did some ugly hacks to my CI scripts and would like to remove those 😬

**Comment by paul-dingemans** [comment]
I cannot release on request as everybody want a release as soon as their problem is solved ;-)
But you're lucky as I already has plans to release this week. But, I need to fix a couple of things before I do so. So it might take a little longer.
