### ISSUE TITLE
Styling for context receiver

### ISSUE THREAD

**Issue by chao2zhang** [pinterest/ktlint#1672]
Context receiver was discussed in https://github.com/pinterest/ktlint/issues/1436 and introduced in Kotlin 1.6.20 https://kotlinlang.org/docs/whatsnew1620.html#prototype-of-context-receivers-for-kotlin-jvm

## Expected Rule behavior
Ensure that we have context receiver separated from other declarations based on the code examples in https://kotlinlang.org/docs/whatsnew1620.html#prototype-of-context-receivers-for-kotlin-jvm
Of course when context receiver is added to the coding convention, there is a chance that Kotlin coding convention might suggest against the above.

## Additional information
* Current version of ktlint:
* Styleguide section: There are a few references but no official style guide yet. This means that this rule could wait until context receiver is promoted to stable feature.
 - https://kotlinlang.org/docs/whatsnew1620.html#prototype-of-context-receivers-for-kotlin-jvm has some examples
 - https://github.com/Kotlin/KEEP/blob/master/proposals/context-receivers.md

**Comment by paul-dingemans** [comment]
Absens of coding convention is not really a problem. For now I will look at default IntelliJ IDEA formatter and the sources you have provided.

**Comment by paul-dingemans** [comment]
For now, I have identified a few code sample on which special indentation is needed:

*Context receiver with a list of parameters on separate lines*
Proposed formatting in KtLint:
```
context(
    Foo,
    Bar
)
fun fooBar()
```
Default IntelliJ IDEA formatter however does not indent the `Foo` and `Bar` types, resulting in:
```
context(
Foo,
Bar
)
fun fooBar()
```

*Context receiver with a generic type*
Proposed formatting in KtLint:
```
context(
    FooBar<
        Foo,
        Bar
        >
)
fun fooBar()
```
Default IntelliJ IDEA formatter however does not de-indent the closing ">" , resulting in:
```
context(
FooBar<
    Foo,
    Bar
    >
)
fun fooBar()
```
Although, this can be fixed in KtLint quite easily, I propose to use the IntelliJ IDEA default formatting for now to keep it in sync with other TYPE_ARGUMENT_LISTs which are formatted in this way.

*Context receiver combined with a modifier*
Proposed formatting in KtLint:
```
context(Comparator<T>)
public fun <T> T.compareTo(other: T) = compare(this, other)
```
Default IntelliJ IDEA formatter however indents modifiers, resulting in:
```
context(Comparator<T>)
    public fun <T> T.compareTo(other: T) = compare(this, other)
```
A comparable example on a property has already been submitted as https://youtrack.jetbrains.com/issue/KTIJ-21072/Provide-proper-indentation-on-declarations-with-context-receivers

Please let me know, if you have other examples of context receivers for which special indentation is required.
