### ISSUE TITLE
Cannot disable rules using the new syntax

### ISSUE THREAD

**Issue by Nohus** [pinterest/ktlint#1777]
I'm trying to disable a rule. This editorconfig works fine:

```
root = true

[*.kt]
disabled_rules=package-name
```

This is however marked as deprecated and generates a lot of warning. When trying to use the new syntax:

```
root = true

[*.kt]
ktlint_standard_package-name = disabled
```
 
The rule is not disabled. I am running ktlint through the Spotless Gradle plugin: https://github.com/diffplug/spotless/tree/main/plugin-gradle 
Running either the `spotlessCheck` or `spotlessApply` task.

**Comment by paul-dingemans** [comment]
I believe this is caused by the spotless integration. Spotless specifies the 
`editorConfigOverride` instead of the `editorConfigDefault` parameter in [code block below](https://github.com/Sineaggi/spotless/blob/2eebed3e6fe081267f5b29daca8ed7e275bafa11/lib/src/compatKtLint0Dot48Dot0/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot0Adapter.java#L101):
```
return KtLint.INSTANCE.format(new KtLint.ExperimentalParams(
				name,
				text,
				allRuleProviders,
				userData,
				formatterCallback,
				isScript,
				false,
				EditorConfigDefaults.Companion.getEMPTY_EDITOR_CONFIG_DEFAULTS(),
				editorConfigOverride,
				false));
```
As a result, the settings in your `.editorconfig` file are overriden by the configuration specified by Spotless.

**Comment by bcmedeiros** [comment]
This use case seems to be working fine for me after https://github.com/diffplug/spotless/issues/1444, make sure you're using `plugin-gradle` 6.13.0

**Comment by Nohus** [comment]
Thank you, updating the Spotless plugin from `6.12.1` to `6.13.0` resolved the issue.
