### ISSUE TITLE
Separate `when` trailling comma from `TrailingCommaOnDeclarationSite`

### ISSUE THREAD

**Issue by bcmedeiros** [pinterest/ktlint#1844]
## Expected Rule behavior
I currently want to enable `TrailingCommaOnDeclarationSite` in my projects, but besides enabling trailing comma for function declarations, it also makes `when` blocks that look like this:
```
fun convertType(typeString: String): Type = when (typeString) {
    "A" -> Type.A
    "B" -> Type.B
    "C",
    "D" -> Type.Other
}
```

be converted to:
```
fun convertType(typeString: String): Type = when (typeString) {
    "A" -> Type.A
    "B" -> Type.B
    "C",
    "D",
    -> Type.Other
}
```

I understand that is the only way to enforce trailing commas in such `when` blocks, and I also understand that's how `ij_kotlin_allow_trailing_comma` works, but this is very ugly and harder to read.

I'd like this to be an optional behaviour of `TrailingCommaOnDeclarationSite`, or ideally be a different rule altogether.

## Additional information
* Current version of ktlint: 0.48.2

**Comment by paul-dingemans** [comment]
The arrow is pushed down because `C` and `D` are already on different lines. If the statement was written like below, it would not have happened:
```
fun convertType(typeString: String): Type = when (typeString) {
    "A" -> Type.A
    "B" -> Type.B
    "C", "D" -> Type.Other
}
```
or
```
fun convertType(typeString: String): Type = when (typeString) {
    "A" -> Type.A
    "B" -> Type.B
    "C" -> Type.Other
    "D" -> Type.Other
}
```

> I'd like this to be an optional behaviour of `TrailingCommaOnDeclarationSite`, or ideally be a different rule altogether.

I am not inclined to add optional behavior as that would require a new `.editorconfig` property. Those properties are hard to discover. Also, it will lead to many more requests for other flags for optional behavior wanted by other developers in some other conditions for their use case. KtLint is all about convergence towards a consistent and predictable code style. Having said that, the first alternative solution I described above would violate that principle as well.

Splitting the `TrailingCommaOnDeclarationSite` in multiple rules can be an alternative to consider. It would at least be more discoverable as linting would show the name of the rule which could be suppressed or entirely be disabled. But, in this case I expect the disadvantage of code duplication to be too big.

Sometimes, it just takes a little while to get used to a new code style.
