### ISSUE TITLE
Provide a simpler convenience API for writing rules

### ISSUE THREAD

**Issue by eygraber** [pinterest/ktlint#1984]
[Slack conversation](https://kotlinlang.slack.com/archives/CKS3XG0LS/p1682536476209099)

When writing rules, I expect to have to do custom traversal of the AST in some cases. However, the majority of the time it seems like there's a lot of non trivial repetition across rules (e.g. traversing the AST to find a `when` vs having a `visitWhen` function).

Detekt has some nice abstractions around working with PSI and `KtFile`. Looks like most of that is supplied through the [Kotlin compiler's KtVisitorVoid](https://github.com/JetBrains/kotlin/blob/master/compiler/psi/src/org/jetbrains/kotlin/psi/KtVisitorVoid.java) and then some wiring through [detekt's BaseRule](https://github.com/detekt/detekt/blob/main/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/BaseRule.kt).

Having the convenience functions from KtVisitorVoid are very helpful and make development simpler.

**Comment by paul-dingemans** [comment]
Very interesting idea for 1.0

**Comment by paul-dingemans** [comment]
I have investigated it. Sofar, I cannot find a way to implement KtVisitorVoid without loosing ktlint functionality.

When using the KtVisitorVoid, the traversal of the nodes in the AST is delegated to the KtVisitorVoid instead of using ktlint's AST traversal mechanism. This results in loosing the ability to suppress certain rules on specific code constructs.

Without implementing KtVisitorVoid, this can be demonstrated in ktlint internally. The KtVisitorVoid functions have a single parameter:
```
public void visitPrimaryConstructor(@NotNull KtPrimaryConstructor constructor) {
```
while Ktlint calls function below for each ASTNode:
```
public open fun beforeVisitChildNodes(
    node: ASTNode,
    autoCorrect: Boolean,
    emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit,
)
```

I have refactored the method as follows by extract the parameters `autoCorrect` and `emit` to class properties:
```
class Rule { // Simplified
    protected val autoCorrect: Boolean
        get() = ...

    protected val emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit
        get() = ...

    public open fun beforeVisitChildNodes(node: ASTNode)
}
```

I have refactored both `RuleExecutionContext` to initialize the `autoCorrect` and `emit` before starting traversal of the rule. Also, I have refactored a single rule to use the new signatures. All worked well, until I ran the entire suite of unit tests. Out of 2000+ unit tests, 33 of them were failing. All failing tests had a code sample containing an `Suppress` annotation to suppress a ktlint rule. For example:
```
val fooWithIndentationFixing1: String =
    "foo" +
        "bar"
@Suppress("ktlint:standard:indent")
val fooWithIndentationFixingSuppressed: String =
    "foo" +
    "bar"
val fooWithIndentationFixing2: String =
    "foo" +
        "bar"
```
The code above produced a lint violation on block:
```
@Suppress("ktlint:standard:indent")
val fooWithIndentationFixingSuppressed: String =
    "foo" +
    "bar"
```
while no violation was expected as it is suppressed with an annotation.

This problem is caused by moving the `autoCorrect` parameter to a property of the `Rule` class and by that make it a constant for all nodes in the class instead of determining per node whether the rule needs to be suppressed for the rule. To solve this, the suppression handling would need to be moved to the Rule class which I am not willing to do as it would make the functionality public. Also, this change will be a breaking and needs changes in all rules.

KtVisitorVoid can not be implemented until above can be solved in acceptable way.

**Comment by eygraber** [comment]
@paul-dingemans would it be possible to create a base class for `Rule` and move suppression handling there in a way that isn't visible from subclasses?

**Comment by paul-dingemans** [comment]
You made me thinking about this issue again.

I found a way to work around the problem without moving the suppression handling to a different module. But is really means that a lot of boilerplate code has to be provided in ktlint. I have to find a way to generate this code to keep things maintainable. The idea is as follows:

Next to the standard `beforeVisitChildNodes` function
```
    public open fun beforeVisitChildNodes(
        node: ASTNode,
        autoCorrect: Boolean,
        emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit,
    ) {}
```
the rule class (or its base class) had to provide an additional function for each `Kt`-construct. Examples:
```
    /**
     * This method is called on a node of element type 'IF' in the AST before visiting the child nodes.
     *
     * @param ktIfExpression the [KtIfExpression] of a node with element type 'WHEN'
     * @param autoCorrect indicates whether rule should attempt autocorrection
     * @param emit a way for rule to notify about a violation (lint error)
     */
    @Suppress("unused")
    public open fun beforeIfExpression(
        ktIfExpression: KtIfExpression,
        autoCorrect: Boolean,
        emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit,
    ): Unit =
        beforeVisitChildNodes(ktIfExpression.node, autoCorrect, emit)

    /**
     * This method is called on a node of element type 'WHEN' in the AST before visiting the child nodes.
     *
     * @param ktWhenExpression the [KtWhenExpression] of a node with element type 'WHEN'
     * @param autoCorrect indicates whether rule should attempt autocorrection
     * @param emit a way for rule to notify about a violation (lint error)
     */
    @Suppress("unused")
    public open fun beforeWhen(
        ktWhenExpression: KtWhenExpression,
        autoCorrect: Boolean,
        emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit,
    ): Unit =
        beforeVisitChildNodes(ktWhenExpression.node, autoCorrect, emit)
```

The `KtlintRuleEngine` will call the new dispatcher function `beforeNode` instead of `beforeVisitChildNodes`:
```
    public fun beforeNode(
        node: ASTNode,
        autoCorrect: Boolean,
        emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit,
    ) {
        when(node.elementType) {
            IF ->
                node.psi.safeAs<KtIfExpression>()?.let { return beforeIfExpression(it, autoCorrect, emit) }
            WHEN ->
                node.psi.safeAs<KtWhenExpression>()?.let { return beforeWhen(it, autoCorrect, emit) }
        }
        // In case no mapping exists for the element type, or if the PSI of the node could not safely be cast to the Kt-type, then fall back
        // on the generic handler.
        beforeVisitChildNodes(node, autoCorrect, emit)
    }
```

And the same has to be done for the `afterVisitChildNodes`. Based on some configurartion it should be doable to a generate a class that contains those functions.

**Comment by paul-dingemans** [comment]
@eygraber See explanation in #2158 why I this will not be implemented in ktlint with the solution provided in the PR. The performance downgrade is not acceptable for the small benefit of rule developers.
