### ISSUE TITLE
kotlinx.* import is expected to be ordered before kotlin.* imports

### ISSUE THREAD

**Issue by hnorkowski** [pinterest/ktlint#2167]
## Expected Behavior

These imports are in lexicographic order and in the order that Intellij reordering produces:
```kt
import kotlin.io.encoding.Base64
import kotlinx.html.a
```

## Observed Behavior

`gradle ktlintCheck` error:
```
Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end (import-ordering)
```

This is the order that ktlintCheck accepts:
```kt
import kotlinx.html.a
import kotlin.io.encoding.Base64
```

## Your Environment

* Version of ktlint used: 11.5.0

**Comment by paul-dingemans** [comment]
You have specified the ktlint_gradle plugin version instead of ktlint version number. Also, you have not provided information about the `.editorconfig` settings.

But, I expect the following:
* You are using code style `intellij_idea` (previously `official`)
* You have not set property `ij_kotlin_imports_layout` in `.editorconfig`

With settings above, the imports are ordered in same order a required by IntelliJ IDEA formatter. The message above `Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end (import-ordering)' means that imports need to be ordered as:
* all imports, except `java.*`, `javax.*` and `kotlin.*` sorted alphabetically. As `kotlinx.*` is not listed here, they are to be sorted in this group.
* all imports in group `java.*` sorted alphabetically
* all imports in group `javax.*` sorted alphabetically
* all imports in group `kotlinx.*` sorted alphabetically

So according to this, your imports are not sorted as expected. You can overwrite `ij_kotlin_imports_layout` in `.editorconfig`. See https://github.com/pinterest/ktlint/blob/c7a2b09680a907a21bf3e4493b6fc3f4dbf22174/ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/importordering/ImportOrderingRuleCustomTest.kt for examples what is possible.

**Comment by hnorkowski** [comment]
I did not provide a .editorconfig file because I am not using one. As far as I understand that its a plugin for IntelliJ and I am not using it.

Here is an image of my import settings in IntelliJ if thats helpful for you:
![grafik](https://github.com/pinterest/ktlint/assets/24483415/b1c94962-5ef7-4f6a-8077-793af8ee3873)

If not you might want to add a more verbose explanation about the .editorconfig file to your issue template.

Your assumption that I am using kotlin's code style `official` is correct.

But my question is: When `javax.*` and `kotlin.*` are getting an exception why no `kotlinx.*`? This makes no sense to me and imports ordered without that exception are horrible to read.

**Comment by paul-dingemans** [comment]
At the time this feature was build, this was the default in IntelliJ IDEA: https://github.com/pinterest/ktlint/blob/33bc94e7575d0fab74ef6613cd9715d1efc83344/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ImportOrderingRule.kt#L200
```
        /**
         * Default IntelliJ IDEA style: Alphabetical with capital letters before lower case letters (e.g. Z before a),
         * except such groups as "java", "javax" and "kotlin" that are placed in the end. Within the groups the alphabetical order is preserved.
         * Alias imports are placed in a separate group in the end of the list with alphabetical order inside.
         * No blank lines between groups.
         *
         * https://github.com/JetBrains/kotlin/blob/ffdab473e28d0d872136b910eb2e0f4beea2e19c/idea/formatter/src/org/jetbrains/kotlin/idea/core/formatter/KotlinCodeStyleSettings.java#L87-L91
         */
        private val IDEA_PATTERN = parseImportsLayout("*,java.**,javax.**,kotlin.**,^")
```

The link to `KotlinCodeStyleSettings` works up until [Kotlin 1.5.32](https://github.com/JetBrains/kotlin/blob/v1.5.32/idea/formatter/src/org/jetbrains/kotlin/idea/core/formatter/KotlinCodeStyleSettings.java). After that version, the file is gone. But, I don't know wether it has been replaced by something else. The Ktlint rule tries to mimic the default behavior of IntelliJ. 
When I create a new Kotlint project with IntelliJ IDEA `2023.2` the `kotlinx` is still not listed as exception. So it will not be added to `ktlint`.
