### ISSUE TITLE
Leave cli parameter `disabled-rules`

### ISSUE THREAD

**Issue by nulls** [pinterest/ktlint#2397]
Diktat uses `KtLint` to run diktat as CLI: `ktlint -R ditkat.jar --disabled-rules=standard`. Now we see the following output:
```
15:04:38.861 [main] WARN com.pinterest.ktlint.cli.internal.KtlintCommandLine - Parameter `--disabled-rules is deprecated, and will be removed in Ktlint 1.1. The disabled rules have to be defined as '.editorconfig' properties. See https://pinterest.github.io/ktlint/1.0.0/faq/#how-do-i-enable-or-disable-a-rule
```

## Expected Behavior
- Leave this parameter
- Disable all standard rules by prefix instead of setting all rule names 

## Current Behavior
- Disable only a single rule, not all standard rules

## Additional information
KtLint version 1.0

**Comment by paul-dingemans** [comment]
If Diktat is a CLI which wraps the `Ktlint CLI` it might be better to hook directly to the `KtLintRuleEngine` instead of relying on the `Ktlint CLI`. `KtLintRuleEngine` has functionality in which you can inject properties as if they were read from a real `.editorconfig` file. Also, you will gain more control over how and what to scan.

The idea behind removing the CLI parameters is to keep configuration for ktlint in one single place (the `.editorconfig`).

**Comment by nulls** [comment]
> If Diktat is a CLI which wraps the `Ktlint CLI` it might be better to hook directly to the `KtLintRuleEngine` instead of relying on the `Ktlint CLI`. `KtLintRuleEngine` has functionality in which you can inject properties as if they were read from a real `.editorconfig` file. Also, you will gain more control over how and what to scan.
> 
> The idea behind removing the CLI parameters is to keep configuration for ktlint in one single place (the `.editorconfig`).

Thanks for the response.

I think the issue can be closed.
