### ISSUE TITLE
Switch to pretty printer

### ISSUE THREAD

**Issue by shyiko** [pinterest/ktlint#241]
(resources)
https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.34.2200
https://www.youtube.com/watch?v=g4HXeP_CZbc

**Comment by shyiko** [comment]
@vanniktech https://prettier.io/docs/en/why-prettier.html

**Comment by cable729** [comment]
From what I understand, to complete this fully involves two separate tasks. However, task one does not depend on task two.

1. Create a javascript prettier component similar to https://github.com/thorbenvh8/prettier-java. This involves setting up the javascript/npm structure. It might be good to have this in a separate repo.
2. Implement line-wrapping in the formatter. This is important to the spirit of prettier because a user of prettier does not want to have to modify their code for style purposes. The formatter should do everything for them. Without line-wrapping in ktlint, the user would still have to modify their code for style.

As far as line wrapping is concerned - this can be done by using the algorithms described in the links above, or via a different algorithm. I've been reading the papers above (I found the second to be more useful and easier to digest) and watched the youtube video. I'm working my way through the ktlint code to compare algorithms. I'm not sure yet how compatible the two are.

**Comment by paul-dingemans** [comment]
Closing issue. Idea has not gained any traction in last 2.5 years. Also it is not clear what OP wanted to achieve,
