### ISSUE TITLE
try-catch comment causing red code on format

### ISSUE THREAD

**Issue by TWiStErRob** [pinterest/ktlint#2427]
## Expected Behavior
Unsure, but definitely still compiling.

## Observed Behavior
```kotlin
fun f() {
    try {
        something()
    } // Blah blah about exception handling. catch (e: IOException) {
        handle(e, 1)
    } catch (e: RuntimeException) {
        handle(e, 2)
    }
}
```

## Steps to Reproduce
`ktlint --format f.kt`

```kotlin
fun f() {
    try {
        something()
    } // Blah blah about exception handling.
    catch (e: IOException) {
        handle(e, 1)
    } catch (e: RuntimeException) {
        handle(e, 2)
    }
}
```

## Your Environment

* Version of ktlint used: 1.0.1
* Relevant parts of the `.editorconfig` settings: none
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): ktlint CLI
* Version of Gradle used (if applicable): N/A
* Operating System and version: Windows 10

**Comment by paul-dingemans** [comment]
The comment `// Blah blah about exception handling.` should be moved inside the `try` or in the `catch` as it is unclear from the AST structure where it refers. In this case, based on the comment text itself it is clear that it does not belong in the `try`. But, it is still unclear whether it refers to a single catch or to all catches. So this actually needs to be forbidden.

Ktlint definitely makes your code sample not compiling anymore. Will be fixed in next release.

**Comment by TWiStErRob** [comment]
Yep, that's what I did. In the real case (see linked right above your comment) it was actually referring to one of the `catch` clauses. Note that the linked code went through a J2K auto-conversion, here's the original code for reference which actually shows that it was meant for a subset of `catch`s.

https://android.googlesource.com/platform/tools/base/+/6c21fa43c56804ab5f4d3a3fc59b5c1158750fa6/resource-repository/main/java/com/android/resources/base/RepositoryLoader.java#545
