### ISSUE TITLE
Ignored .editorConfig max_line_length' in Spring Boot Kotlin Project with Spotless

### ISSUE THREAD

**Issue by jegalirisoft** [pinterest/ktlint#2458]
We need to set the 'max_line_length' in the editorConfig file and the editorConfigOverride function. Currently, the '.editorConfig' 'max_line_length' property is not being recognized. However, when we override the editorConfig property in the Gradle files, it works fine. Please address and fix this issue."

```
root = true

[*]
charset = utf-8
trim_trailing_whitespace = true
end_of_line = lf
max_line_length = 140

[*.{kt,kts}]
ij_kotlin_allow_trailing_comma = true
ij_kotlin_allow_trailing_comma_on_call_site = true
ij_kotlin_code_style_defaults = KOTLIN_OFFICIAL
```

```
    spotless {
    kotlin {
        target("src/**/*.kt")
        targetExclude("**/build/**/*.kt")
        targetExclude("bin/**/*.kt")
        ktfmt().kotlinlangStyle()
        // com.pinterest.ktlint:ktlint-cli
        ktlint("1.1.0").setEditorConfigPath("$rootDir/.editorconfig")
//            .editorConfigOverride(
//                mapOf(
//                    "max_line_length" to 140,
//                ),
//            )
        trimTrailingWhitespace()
        endWithNewline()
        licenseHeaderFile("$rootDir/spotless/spotless.license.kt")
    }}```

**Comment by paul-dingemans** [comment]
I have no knowdlegde of Spotless. What is the content of file `$rootDir/.editorconfig`?

Have you asked you question in the Spotless project first? They know how they have integrated with ktlint and are in best position to determine whether this issue is caused by Spotless or by Ktlint. Ktlint does respects the `max_line_length` when set.
