### ISSUE TITLE
--reporter/--ruleset Java 9+ compatibility

### ISSUE THREAD

**Issue by josephmbeveridge** [pinterest/ktlint#259]
I checked out the repo and ran `./gradlew build` in `ktlint-ruleset-template` to generate the jars. I then tried running ktlint with all of those jars against a kotlin class and received

``` java
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at com.github.shyiko.ktlint.Main.loadJARs(Main.kt:567)
	at com.github.shyiko.ktlint.Main.main(Main.kt:253)
```

I can't see anything wrong with the jar structure or the paths I am using, but I'm guessing I have done something wrong.

The command I used was:
`ktlint -R build/libs/ktlint-ruleset-template.jar src/main/kotlin/yourpkgname/NoVarRule.kt`

I also tried using the sources jar.

**Comment by shyiko** [comment]
You must be running Java 9+. 
https://github.com/shyiko/ktlint/blob/84d8931828311bd1bbcc7521b6524ef906d3135b/ktlint/src/main/kotlin/com/github/shyiko/ktlint/Main.kt#L642-L644
The fix is relatively simple: we need to use a separate class loaded instead of hijecking SystemClassLoader.
If you have the time for a PR - I can promise a release within 24h of "Merge".

**Comment by josephmbeveridge** [comment]
Thanks for the quick response.

You're right, it looks like I am on Java 9. I'll see if I have time to look into fixing this.
