### ISSUE TITLE
kscript comment-style directives are marked as errors with ktlint

### ISSUE THREAD

**Issue by 0legg** [pinterest/ktlint#273]
Similar to https://github.com/shyiko/ktlint/pull/212 — [kscript](https://github.com/holgerbrandl/kscript) uses comment-style directives and relying on no space after the double slash.

I'm not sure whether this issue belongs to ktlint of kscript though — my gut feeling is it's kscript who needs to adopt the change, but I'll cross-create tickets in both repos.

Ref https://github.com/holgerbrandl/kscript/issues/153

**Comment by 0legg** [comment]
https://github.com/google/google-java-format/blob/4fa9d4967170109b1f8b238c12bb42ee9d26ba88/core/src/main/java/com/google/googlejavaformat/java/JavaCommentsHelper.java#L105-L108 For reference, GCF excludes few predefined annotation-alike comments from formatting, ktlint does the same for noinspection.

**Comment by shyiko** [comment]
To summarize:

right now user has an option to
- turn off `comment-spacing` check by prepending `/* ktlint-disable comment-spacing */` at the top of the script.
- (or) use [@file:* instead of //...](https://github.com/holgerbrandl/kscript#annotation-driven-script-configuration) (https://github.com/holgerbrandl/kscript/issues/153#issuecomment-416477547).

ktlint could
- provide a way to exclude certain patterns (e.g. `//(DEPS|ENTRY|...)`) (this would require a config file which we don't currently have)
- auto-detect kscript (`#!/usr/bin/env kscript`) (allow `//(DEPS|ENTRY|...)` when detected) (https://github.com/holgerbrandl/kscript#use-entry-to-run-applications-with-main-method would not be covered)

kscript could
- support `//\s*(DEPS|ENTRY|...)` (https://github.com/holgerbrandl/kscript/issues/153#issuecomment-416606160).
- support `// kscript-deps ...`, `// kscript-entry ...`, etc.
