### ISSUE TITLE
ktlint_standard_string-template-indent incompatbile with multi-dollar interpolation

### ISSUE THREAD

**Issue by mgroth0** [pinterest/ktlint#2885]
It is a bit difficult to create a reproducer because the latest release of ktlint uses an embedded kotlin version that throws errors when it encounters `$$` before a string. But if you use an embedded kotlin compiler version of `2.1.0` with ktlint `1.4.1` and run it on this

```kotlin
fun main() {
    $$"""
        hello world
    """.trimIndent()
}
```

You end up with

```kotlin
fun main() {
    $$
    """
        hello world
    """.trimIndent()
}
```

Which is a syntax error.

Disabling `ktlint_standard_string-template-indent` is preventing this.

**Comment by paul-dingemans** [comment]
As documented on https://kotlinlang.org/docs/strings.html#multi-dollar-string-interpolation the number of `$` before the multiline string can vary. Using `$$` means that single `$` can be used in the string without it being used for interpolation.  Using `$$$` means that both `$` and `$$` can be used in the string. The multidollar prefix can be recorgnized in the AST as shown below:
<img width="865" alt="Screenshot 2024-12-02 at 17 40 08" src="https://github.com/user-attachments/assets/81016ba9-2b68-4d70-a8d9-5a7436f9bee9">

Note that compiler flag `-Xmulti-dollar-interpolation` needs to be enabled in order to use this feature.
