### ISSUE TITLE
Promote IndentationRule to standard ruleset

### ISSUE THREAD

**Issue by shashachu** [pinterest/ktlint#475]
These have been in experimental for a couple releases. At Pinterest we've had the indentation rule on since its release.

@bethcutler thoughts? I believe you're using the experimental `IndentationRule` internally as well.

**Comment by bethcutler** [comment]
I'm definitely in favor of promoting these to the standard ruleset.  I think we would prefer not to be using the experimental ruleset... once these two rules are standardized we will move back to just the standard set.

So far we've only come across two issues with the indentation: #433 (which has been fixed) and #479 (which I've just now gotten around to adding... it's a more debatable, open-ended issue).  Otherwise they've worked very well for us.
