### ISSUE TITLE
Remove the wrong Unit return value

### ISSUE THREAD

**Issue by XhstormR** [pinterest/ktlint#488]
I have a class called Unit:
```kotlin
class Unit(
        var name: String
) : Base()
```

Then I have a function:
```kotlin
    fun updateUnit(moduleId: Long, id: Long, request: UnitAddRequest): Unit {
        val unit = unitRepository.findByModuleIdAndId(moduleId, id)
        unitMapper.updateFromRequest(request, unit)
        return unit
    }
```

After formatting, it became, and compilation fails:
```kotlin
    fun updateUnit(moduleId: Long, id: Long, request: UnitAddRequest) {
        val unit = unitRepository.findByModuleIdAndId(moduleId, id)
        unitMapper.updateFromRequest(request, unit)
        return unit
    }
```

**Comment by JLLeitschuh** [comment]
Related: #77 
The discussion that @shyiko and I had in #77 is 100% relevant here.

**Comment by XhstormR** [comment]
I didn't find a solution, just find `: Unit =` will keep `Unit`, but I am `: Unit {}`

**Comment by shashachu** [comment]
Thanks for the context, JLLeitschuh. 

This seems like a tough one to fix; we could see if there was an import called `Unit` in the file but that wouldn't work if the `Unit` class was in the same package and didn't need an import.

If it were me I'd probably rename the `Unit` class to something else since it's a keyword in Kotlin.

**Comment by JLLeitschuh** [comment]
I agree with @shashachu. I'd advise avoiding collisions with names like `Unit`, & `Nothing`.

**Comment by XhstormR** [comment]
Ok, I get it.
