### ISSUE TITLE
Max line length errors when using an EOL comment

### ISSUE THREAD

**Issue by shashachu** [pinterest/ktlint#536]
Comments that are alone on a line will not trigger max-line-length error, but EOL comments with other code on the line will. Unsure if this is desired behavior or bug.

**Comment by christinalee** [comment]
If we presume that line length caps are present for readability purposes, I'd argue that the readability of documentation is important as well. Since we haven't enforced this in the past it would likely cause many new errors, so the annoyance factor would be high, but I think enforcing line length universally is desirable behavior.

If we agree on this as a direction, I can implement it and put it under experimental checks.

**Comment by paul-dingemans** [comment]
This issue has become stale as it has not been updated in almost 3 years.
