### ISSUE TITLE
Additional code safety checks (disallow not-null assertion operator and force casting)

### ISSUE THREAD

**Issue by EricKuck** [pinterest/ktlint#594]
I've created two new rules for use at my company that I feel could be good additions for most Kotlin developers. Both are centered around code safety.

First, we have a rule to disallow the not-null assertion operator (`!!`). There are always safer ways to do things, and even if having null _should_ cause a crash, it's clearer to explicitly throw an Exception when they're encountered.

Second, we have a rule to disallow force casting (using `foo as Bar` instead of `foo as? Bar`). Again, there are safer ways to do this, and if this is truly exceptional behavior, it's clearer to explicitly throw Exceptions.

Would others be interested in one or both of these rules? If so, which ruleset should they be added to?

**Comment by JakeWharton** [comment]
I use each of these regularly and encourage their use. Both justifications are "it's clearer to explicitly throw an exception" which I don't really buy as an argument.

In Java I would write:
```java
Thing thing = getSomeThing();
if (thing == null) {
  throw new NullPointerException("thing");
}
```
when I need to maintain the non-null invariant.

In Kotlin, not only can I write the shorter:
```kotlin
val thing = getSomeThing()!!
```
but I also get a better exception message for free as it includes (for now) the expression which produced the null rather than the local name (which is mostly useless).

It makes no sense to me to write
```kotlin
val thing = requireNonNull(getSomeThing()) { "thing" }
```
or
```kotlin
val thing = getSomeThing() ?: throw NullPointerException("thing")
```
when `!!` produces the exact same behavior in a more terse package. After all, isn't that the point of most of Kotlin? Reducing the verbosity of common patterns of Java?

If we're arguing against `!!` for being "bad" because it's a shorter version of a null check and throwing an exception, I would also like to ban `?.` for being a shorter version of a null check and doing nothing. The safe call operator is _dramatically_ worse than `!!` if we're purely focusing on syntactical shortenings that Kotlin provides. This operator silently allows null to propagate in your system. In the same way that we can't know whether `!!` was explicit, we can't know whether `?.` was explicit and thus we would have to force people to use locals and normal null checks.

I, of course, do not believe that either are bad. But I do have a really hard time seeing how you can ban `!!` without also `?.` since the former will thankfully at least always throw. In fact, by banning only `!!` you my inadvertently push people to `?.` which is entirely the wrong thing which you should fail over to.

The choice between `!!`, `?.`, or any other handling of null is one which always requires thought. I do not believe that you can categorically replace the use of one of these with a longer construct, and especially not one without the other. These wouldn't be in the language if we weren't meant to use them. Someone misusing them is not a function of the operators being bad, it's an education issue. Certainly just about anything else can be misused to the same degree as well.

For `as` and `as?` I have the same general reasoning. I don't see value in categorically banning a language feature.

**Comment by EricKuck** [comment]
Those are totally valid arguments. It's interesting that force unwraps (swift's version of the not-null assertion operator) and force casts are both considered bad in the swift world, but not in the kotlin world. The swift equivalent of this library (swiftlint) has guards against both operators as [defaults](https://github.com/realm/SwiftLint/blob/master/Rules.md) and everyone seems to agree that that's the right thing to do. Whether these rules are right or wrong for the kotlin community isn't my call. It was a good addition to our codebase, but if others feel they're not good rules for kotlin I'm happy to close the issue.

**Comment by Tapchicoma** [comment]
Project goal is to provide consistent _code style_. From this perspective usages of `!!` or `as?` are totally valid. 

You rules are more related to the code quality that goes into the field of [detekt](https://github.com/arturbosch/detekt).
