### ISSUE TITLE
`disabled_rules` does not respect `max_line_length` in `.editorconfig`

### ISSUE THREAD

**Issue by ZakTaccardi** [pinterest/ktlint#696]
`disabled_rules` and `max_line_length` don't seem to play nicely with one another.

**Use Case**
I would like to inform my IDEA to hard wrap at 120 (Android Studio), but not fail `ktlint` when the developer chooses to leverage `> 120` lines for a string literal

**To reproduce**

`.editorconfig` file:

```editorconfig
[*.{kt,kts}]
max_line_length = 120  # informs Android Studio to hard wrap at 120

disabled_rules=max_line_length
```

Running ktlint over a file with a line over a `120`  limit throws the following exception. 

```
Exceeded max line length (120) (cannot be auto-corrected) (max-line-length)
```

It is my understanding that because `max_line_length` is disabled, `ktlint` should consider the rule as if it were `off`

**Comment by ZakTaccardi** [comment]
My bad - it seems `max-line-length` is valid for `disabled_rules` (`-` vs `_`)

**Comment by rethab** [comment]
I also suspected ktlin was not taking the disabled rules into account even though I was sure I disabled the `max-line-length` correctly.

In my case, the problem turned out to be that the property `max_line_length` in `.editorconfig` is not only used by the MaxLineLengthRule, but also (among others?) by the ParameterListWrappingRule.

This means that if you configure the `max_line_length` in `.editorconfig` along with `disabled_rules=max-line-length`, ktlint might still error, like so:
```txt
MyFile.kt:21:113: Parameter should be on a separate line (unless all parameters can fit a single line)
```

In my case, I was fine with formatting those files and the problem went away.
