### ISSUE TITLE
Please share roadmap 

### ISSUE THREAD

**Issue by arhont375** [pinterest/ktlint#962]
Hi, thanks for this project.
Is there any roadmap for ktlint?
I found only one reference to roadmap in [old issue](https://github.com/pinterest/ktlint/issues/398#issuecomment-485831602) but have no idea where to search for this blog post.

Should this be included into the repository/readme somewhere?
Or maybe create milestone `1.0.0` that will show what planned to be implemented in long period of time?

**Comment by Tapchicoma** [comment]
@shashachu probably make sense to set milestone for `1.0.0` version and create issues related to first stable release

**Comment by paul-dingemans** [comment]
Unfortunately I get the feeling that this project is getting stale slowly. The number of open pull requests is rising.  I still would like to contribute to the project, if my pr's are getting merged. I can understand if current maintainers do not have time or energy for the project. Is there any possibility that new maintainers are added so that the project can be revived?

**Comment by shashachu** [comment]
@paul-dingemans apologies for the issues with getting your PRs merged. You're correct that the free time of the maintainers has dropped over the last year, and particularly recently, however we're still committed to the project. I'll put some time into getting the builds green this week.

**Comment by paul-dingemans** [comment]
@arhont375 For now, we will not define a long term roadmap. Main reason is that we have limited capacity to work on the project. Recently, I joined as maintainer on the project. My personal goal it to push the project forward by speeding up the review and merge process and to actively stimulate people to contribute to ktlint.
